### ISSUE TITLE
Scrot not working in Snapcraft

### ISSUE THREAD

**Issue by RobbieTheWagner** [mockingbot/electron-color-picker#12]
When packaged with Snapcraft, Scrot doesn't seem to work, and I get the following:

```
[ERROR] getColor Error: Command failed: /snap/swach/x1/app/resources/app.asar.unpacked/node_modules/electron-color-picker/library/linux/linux-scrot/scrot /run/user/1000/snap.swach/temp-screenshot.png
giblib error: Saving to file /run/user/1000/snap.swach/temp-screenshot.png failed


    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  killed: false,
  code: 2,
  signal: null,
  cmd: '/snap/swach/x1/app/resources/app.asar.unpacked/node_modules/electron-color-picker/library/linux/linux-scrot/scrot /run/user/1000/snap.swach/temp-screenshot.png'
```

Any ideas what the problem might be?

**Comment by RobbieTheWagner** [comment]
It seems it doesn't have permissions. Is there any way to use the system installed `scrot` instead of bundling one up here @dr-js?

**Comment by RobbieTheWagner** [comment]
I'm thinking we need to allow the scrot executable path to be configurable here https://github.com/mockingbot/electron-color-picker/blob/master/source/linux/linux-scrot/index.js#L7 then I think I could bundle my own version of scrot and pass the path. Thoughts?

**Comment by ThatBean** [comment]
Since snap is sort of a linux sandbox, my guess is `scrot` might not be allowed or cannot get the "desktop" screen buffer inside a snap environment.
And if it does work the resulting desktop screenshot may not include the full desktop, maybe sort of like getting the whole system `df -h` inside a docker container...

With MacOS and Ubuntu pushing more and more permission and sand-boxing, my bet is getting desktop screenshot correctly will get harder if not impossible.

**Comment by ThatBean** [comment]
Related snap issue: https://forum.snapcraft.io/t/cannot-publish-an-electron-app/17493/43

**Comment by RobbieTheWagner** [comment]
@ThatBean I wonder if we could use something else instead of scrot? I am unsure what this package is using, but they distribute on Snap https://github.com/stuartlangridge/ColourPicker

**Comment by ThatBean** [comment]
My guess is how they config the `snap/snapcraft.yaml`? (not tested snaps yet)
https://github.com/stuartlangridge/ColourPicker/blob/34e4f32400f991ac9cc47684af11a670a4533e33/snap/snapcraft.yaml#L38-L42
https://snapcraft.io/docs/interface-management
https://snapcraft.io/docs/dbus-interface

**Comment by ThatBean** [comment]
And about replacing `scrot`, I'm not C expert, but checking https://github.com/resurrecting-open-source-projects/scrot/blob/master/src/scrot.h#L34-L43, it seems `scrot` gets screenshot from X11 interface as a `27.3 KB` binary.

So similar X11 screenshot binary may not work in snaps either?

Another option is to rewrite and use Electron `desktopCapturer` from the renderer process (browser window) to get a screenshot, this may save more bytes, but whether that will work under snaps is also unknown:
- https://www.electronjs.org/docs/api/desktop-capturer
- https://ourcodeworld.com/articles/read/280/creating-screenshots-of-your-app-or-the-screen-in-electron-framework

**Comment by RobbieTheWagner** [comment]
@ThatBean so you think we need to allow some kind of `dbus` connection? If you have something in mind, I am happy to try it to see if it works.

As for maybe switching to `desktopCapturer`, I think that could potentially be a good idea, but it may also be blocked in Snap. I am not sure.

**Comment by ThatBean** [comment]
Or maybe the x11 config: https://github.com/stuartlangridge/ColourPicker/blob/34e4f32400f991ac9cc47684af11a670a4533e33/snap/snapcraft.yaml#L46-L57
After skimming the doc, `slot` looks like a connector for interact with outside snap/program.

For testing maybe just put all permission-ish config in first, and test if scrot in snaps can output a desktop screenshot successfully. Then trim down the extra config.

**Comment by RobbieTheWagner** [comment]
@ThatBean the problem I ran into is the scrot binary is not executable. We need to whitelist it in some way.

**Comment by RobbieTheWagner** [comment]
If anyone else is hitting this, this is how we fixed it:

```json
  "build": {
    "productName": "Swach",
    "linux": {
      "icon": "./resources/icon.png",
      "category": "Development",
      "description": "A robust color management tool for the modern age.",
      "synopsis": "A robust color management tool for the modern age.",
      "target": [
        "snap"
      ]
    },
    "snap": {
      "stagePackages": [
        "default",
        "giblib1",
        "libimlib2",
        "libx11-6",
        "libxcursor1",
        "libxfixes3",
        "scrot"
      ]
    }
  }
```
