### ISSUE TITLE
Issues on MacOS

### ISSUE THREAD

**Issue by rwwagner90** [mockingbot/electron-color-picker#6]
Hello,

Thanks for this great library! In dev mode it works great, but when I package my app, I get a prompt from Mac saying `would like to record keystrokes from any application` and I have gone into system preferences to try to enable it, but it does not seem to work.

I know there is the custom packaging stuff we need to do, and maybe I messed that up, I am not sure. I tried copying the `electron-color-picker` directory from node_modules into my resources folder and requiring it from there with:

```js
const { getColorHexRGB } = require('../resources/electron-color-picker');
```

Is this the correct thing to do or is the resources folder you are describing in the output somewhere?

Is the permissions issue expected?

**Comment by rwwagner90** [comment]
I finally figured out, after hours of debugging, how to copy into resources with electron-packager. They provide an `extraResource` option so I can do:

```js
const electronColorPickerPath = join(
  __dirname || resolve(dirname('')),
  'node_modules/electron-color-picker'
);

...
 extraResource: [
      electronColorPickerPath
    ],
...
```

However, even with this, the picker does not work. I still get the popup asking `would like to record keystrokes from any application` every time I open the picker. I have given it permissions, and it still shows up every time. I believe this is not even the correct permissions and that the new ones needed are like permission to record screen etc.

Any ideas how I can get this to work?

```

**Comment by rwwagner90** [comment]
I was finally able to click `open system preferences` on the popups and now it works! I think the issue here is when it asks for permissions, it also shows the color picker. I think it should wait until permissions are granted. Is there a way to ensure permissions before showing the picker?

**Comment by ThatBean** [comment]
Were the test done on macOS 10.15?

The darwin permission problem may be fixed with `Add support for macOS 10.15 new permission politics` from [mockingbot/mb_colorpicker_desktop_native@v2.0.0](https://github.com/mockingbot/mb_colorpicker_desktop_native/releases/tag/v2.0.0) (the darwin binary for color picking)

**Comment by rwwagner90** [comment]
@ThatBean yes, I am on macOS 10.15. I believe the main issue here is the color picker shows up immediately before waiting for permissions. It would be nice if we could have `getColorHexRGB` trigger the request for permissions first or better yet have a way to programmatically ask for permissions, so that I can ask the user to give permissions before even using my app.

How would I use that new v2 release with this package? I am happy to try it out.

**Comment by ThatBean** [comment]
It might take a while for us to update the change to darwin v2 binary.(currently I have no darwin access)

From the [sample file](https://github.com/mockingbot/mb_colorpicker_desktop_native/blob/dev/index.html#L88), it seems like there's 2 permission check mode: peek-status and ask-for-popup. So some extra JS logic is needed for those extra check.

**Comment by rwwagner90** [comment]
@ThatBean is there anything I can do to help?

**Comment by ThatBean** [comment]
Will find sometime to do a code clear up first to the mockingbot/mb_colorpicker_desktop_native sample JS, then add the permission code here and do a major version update.

Should be able to do this in this week. @rwwagner90 Can you test the darwin dev version when it's ready, if you got time?

**Comment by rwwagner90** [comment]
@ThatBean I am happy to test things out when they are ready. Just let me know!

**Comment by ThatBean** [comment]
Progress track:
- mockingbot/mb_colorpicker_desktop_native
  * PR for JS code sort: https://github.com/mockingbot/mb_colorpicker_desktop_native/pull/1
  * ISSUE for doc behavior: https://github.com/mockingbot/mb_colorpicker_desktop_native/issues/2

**Comment by ThatBean** [comment]
New dev version is out
Try the updated [./example/](https://github.com/mockingbot/electron-color-picker/tree/master/example)
Or update code with new permission func & test with [electron-color-picker@0.2.0-dev.0](https://www.npmjs.com/package/electron-color-picker/v/0.2.0-dev.0)

**Comment by ThatBean** [comment]
Fixed example & some platform detecting bug in `0.2.0-dev.1`

**Comment by ThatBean** [comment]
Progress track:
- mockingbot/electron-color-picker
  - PROBLEM: providing the required `--bundle-id` for permission checking is kind of tricky:
    - use the terminal app bundle id when debugging from in terminal
    - use the packaged app bundle id when open a release app by Finder or start
- mockingbot/mb_colorpicker_desktop_native
  - ISSUE for trying to drop `--bundle-id` requirement: https://github.com/mockingbot/mb_colorpicker_desktop_native/issues/4

**Comment by ThatBean** [comment]
Fixed bundle id with auto detecting script in `0.2.0-dev.2`

Try the updated [./example/](https://github.com/mockingbot/electron-color-picker/tree/master/example)
Or update code with new permission func & test with [electron-color-picker@0.2.0-dev.2](https://www.npmjs.com/package/electron-color-picker/v/0.2.0-dev.2)

@rwwagner90 should be good for testing

**Comment by rwwagner90** [comment]
@ThatBean I am not sure how to test, since I have already granted permissions to my app.

**Comment by ThatBean** [comment]
The permission is granted to the Terminal app when debugging unpackaged Electron
To reset permission from terminal, depending on the Terminal you use:
- `tccutil reset ScreenCapture com.apple.Terminal`
- `tccutil reset ScreenCapture com.googlecode.iterm2`

If you use `electron-packager` to build the App, reset with: `tccutil reset ScreenCapture YOUR.APP.BUNDLE.ID`

Or just go to `System Preference -> Security & Privacy -> Privacy Tab -> Screen Recording` and un-check the App

**Comment by rwwagner90** [comment]
@ThatBean I went into `System Preference -> Security & Privacy -> Privacy Tab -> Screen Recording` and unchecked the app, which does remove the ability to use the color picker on open apps. However, it does not prompt me to enable the setting. Is there a way we could have it ask you to enable permissions? I'm not sure what exactly this new build was supposed to change regarding that.

**Comment by ThatBean** [comment]
You can run the example or check the updated usage in [README.md](https://github.com/mockingbot/electron-color-picker/blob/master/README.md#usage), added 2 more darwin-only async functions for permission check & request:
```js
const darwinScreenPermissionSample = async () => { // darwin only, throw error on other platform (since electron-color-picker@2)
  const { darwinGetScreenPermissionGranted, darwinRequestScreenPermissionPopup } = require('electron-color-picker')

  // initial check
  const isGranted = await darwinGetScreenPermissionGranted()
  console.log('darwinGetScreenPermissionGranted:', isGranted)

  if (!isGranted) { // request user for permission
    const isGranted = await darwinRequestScreenPermissionPopup()
    console.log('darwinRequestScreenPermissionPopup:', isGranted)
  }
}
```

**Comment by rwwagner90** [comment]
@ThatBean I suppose it is not calling that function then. When I uncheck to remove the permissions, I am not prompted to enable them again.

**Comment by ThatBean** [comment]
@rwwagner90 Currently `darwinGetScreenPermissionGranted` and `darwinRequestScreenPermissionPopup` will not be called automatically from `getColorHexRGB`, so extra code & check is needed

Maybe it's better to default to an all-in-one `getColorHexRGB`, and add another `darwinGetColorHexRGB`, will try to add in next version

**Comment by ThatBean** [comment]
Progress track:
- mockingbot/electron-color-picker
  - add detect darwin macOS 10.15
  - merge `darwinGetScreenPermissionGranted`, `darwinRequestScreenPermissionPopup` into `getColorHexRGB`, add another `darwinGetColorHexRGB`
  - test asar package now darwin is single binary

**Comment by rwwagner90** [comment]
@ThatBean I am okay with programmatically calling extra functions to get the permissions. In fact, I would love to be able to do this before the user ever even clicks the color picker, so that when they do click it, it is ready to go.

**Comment by ThatBean** [comment]
Update in `electron-color-picker@0.2.0-dev.7`:
- normal asar packaging should work now, since darwin is single binary, check the updated `example/`
- the exported function name & return value has been changed to the following for better understanding:
    ```js
    export {
      getColorHexRGB, // slower all-in-one
    
      // for more control and customized checks
      DARWIN_IS_PLATFORM_PRE_CATALINA, // darwin only, undefined on other platform
      darwinGetColorHexRGB, // darwin only, throw error on other platform
      darwinGetScreenPermissionGranted, // darwin only, throw error on other platform
      darwinRequestScreenPermissionPopup // darwin only, throw error on other platform
    }
    ```
- for deeper customize, consider checking: https://github.com/mockingbot/electron-color-picker#advanced-usage

**Comment by rwwagner90** [comment]
@ThatBean so does this color picker only work on Catalina?

**Comment by ThatBean** [comment]
It should work and correctly skip the Permission check on pre-Catalina macOS.

Currently the minimum working version is not tested, maybe it's the same as Electron:
> Only 64bit binaries are provided for macOS, and the minimum macOS version supported is macOS 10.10 (Yosemite).
> https://electronjs.org/docs/tutorial/support#macos

**Comment by rwwagner90** [comment]
@ThatBean makes sense. So I just need to use `DARWIN_IS_PLATFORM_PRE_CATALINA` and if that is true, skip the permissions checks and it should still work?

**Comment by ThatBean** [comment]
Yes, that's basically the code: https://github.com/mockingbot/electron-color-picker/blob/master/source/darwin/index.js#L39

**Comment by rwwagner90** [comment]
@ThatBean so is `runColorPicker` called by `getColorHexRGB` and the permissions stuff happens automatically?

**Comment by ThatBean** [comment]
Yes, that's what supposed to happen.

**Comment by rwwagner90** [comment]
I think everything is good to go here then. Thanks so much for all the help and work you put into this!
